BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "User" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"username"	TEXT NOT NULL UNIQUE,
	"password"	TEXT NOT NULL,
	"field_id"	INTEGER
);
CREATE TABLE IF NOT EXISTS "Field" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT NOT NULL,
	"data"	TEXT NOT NULL,
	"notes"	TEXT NOT NULL,
	"account_id"	INTEGER
);
CREATE TABLE IF NOT EXISTS "Account" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"username"	TEXT NOT NULL,
	"password"	TEXT NOT NULL,
	"hiddenPassword"	TEXT NOT NULL,
	"creationDate"	TEXT NOT NULL
);
COMMIT;
